import {WidgetErrorHandler}                    from "../gui/WidgetErrorHandler";
import {
   Ax2Widget,
   Ix2BeforeLogic,
   Ix2Refresh,
   Ix2Resized,
   Ix2OnClear,
   Ix2OnHtml,
   Ix2OnLogic,
   Ix2Destroy, Ix2AfterLogic
} from "./Ax2Widget";
import {Ix2HtmlDecorator}                      from "./Ix2HtmlDecorator";

export interface Ix2State<WIDGET_TYPE extends Ax2Widget = Ax2Widget> {


   /**
    *  Called after initLogic has been completed for this component AND for ALL the child components
    */
   afterChildrenInit?: () => void;

   /**
    *  Called after initLogic has been completed for this component but NOT for any child components
    *  Use the <link>onChildrenInstantiated</link> event if you need all child components to also have been initialized
    */
   afterInitWidgetOnly?: (args:Ix2AfterLogic) => void;

   /**
    * If this is specified, the widget's method (if any) will not be called.
    * Should you need to call the corresponding widget method, you can call it manually from this method
    * by using the widget instance in the parameter
    */
   afterInitLogic ?: (args : Ix2AfterLogic) => void;

   /**
    * If this is specified, the widget's method (if any) will not be called.
    * Should you need to call the corresponding widget method, you can call it manually from this method
    * by using the widget instance in the parameter
    */
   beforeInitLogic?: (args ?: Ix2BeforeLogic) => (void|Promise<void>);

   /**
    * The HTML decoration for the HTML element that of the widget
    */
   deco?: Ix2HtmlDecorator;


   /**
    * Contains all the fields that are generated by the widget initialization code
    */
   gen ?:Ix2StateGenerated<WIDGET_TYPE>

   /**
    * The current children this widget contains
    * @see initialChildren
    */
   children?: Ax2Widget[]


   /**
    * If this is true, the widget will be rendered without using the <link>tagId</link> value as the id of the HTML element.
    * @see tagId
    */
   noTagIdInHtml?: boolean;

   /**
    * Set to true if the existing HTMLElement needs to be destroyed and recreated when refreshing
    */
   resetUIOnRefresh?: boolean;

   /**
    * If true, the resize is tracked for the HTML element of the widget
    */
   resizeTracked?: boolean;


   /**
    * Set to true if the widget is completely static and no refresh should take place
    */
   staticWidget?: boolean;

   /**
    * The unique id of the widget (also used as the id of the HTML element if <link>noTagIdInHtml</link> is false)
    * @see noTagIdInHtml
    */
   tagId?: string;

   onClear?: (args:Ix2OnClear) =>  void ;

   onDestroy?: (args: Ix2Destroy) =>  void ;

   onHtml?: (args:Ix2OnHtml) =>HTMLElement;

   onLogic?: (args : Ix2OnLogic) =>  void;

   onRefresh?: (args ?: Ix2Refresh) =>  void;

   /**
    * Called when the widget is resized (assuming <link>widget.resizeTracked</link> is true)
    * @param evt
    */
   onResized ?: (evt?:Ix2Resized) => void;

   widgetErrorHandler?: WidgetErrorHandler;
}

export interface Ix2StateGenerated<WIDGET_TYPE extends Ax2Widget = any>{



   /**
    * the htmlElement (usually generated by <link>onHtml</link>) that underpins the widget. This is a generated property (usually)
    */
   htmlElement ?: HTMLElement;

   widget?: WIDGET_TYPE;



}

//
// /**
//  * Return true if the default logic should be executed, false if logic should return immediately
//  */
// export type functionCancellableWx2Event = (widget: Ax2Widget<any>) => Promise<boolean>;
//