import {WidgetErrorHandler}                    from "../gui/WidgetErrorHandler";
import {
   Nx2,
   Nx2Evt_BeforeLogic,
   // Nx2Evt_Refresh,
   Nx2Evt_Resized,
   // Nx2Evt_OnClear,
   Nx2Evt_OnHtml,
   Nx2Evt_OnLogic,
   Nx2Evt_Destroy, Nx2Evt_AfterLogic, Nx2Evt
} from "./Nx2";
import {Nx2HtmlDecorator}                      from "./Nx2HtmlDecorator";
import {Elem_or_Nx2} from './Nx2Utils';

export interface StateNx2 {


   /**
    * This method assumes that the state is completely initialized and ready to be used.
    *
    * Useful when overriding in order to customize the state object before calling super.
    *
    * If this is specified, the widget's method (if any) will not be called.
    * Should you need to call the corresponding widget method, you can call it manually from this method
    * by using the widget instance in the parameter.
    *
    *
    */
   onStateInitialized?:(ev:Nx2Evt) => void;

   /**
    *  Called after initLogic has been completed for this component AND for ALL the child components
    */
   onAfterChildrenInit?: () => void;

   /**
    *  Called after initLogic has been completed for this component but NOT for any child components
    *  Use the <link>onChildrenInstantiated</link> event if you need all child components to also have been initialized
    */
   onAfterInitWidgetOnly?: (ev:Nx2Evt_AfterLogic) => void;

   /**
    * If this is specified, the widget's method (if any) will not be called.
    * Should you need to call the corresponding widget method, you can call it manually from this method
    * by using the widget instance in the parameter
    */
   onAfterInitLogic ?: (ev : Nx2Evt_AfterLogic) => void;

   /**
    * If this is specified, the widget's method (if any) will not be called.
    * Should you need to call the corresponding widget method, you can call it manually from this method
    * by using the widget instance in the parameter
    */
   onBeforeInitLogic?: (ev ?: Nx2Evt_BeforeLogic) => (void|Promise<void>);

   /**
    * The HTML decoration for the HTML element that of the widget
    */
   deco?: Nx2HtmlDecorator;

   /**
    * A wrapper element around the HTML element of the widget
    */
   wrapper ?: Nx2HtmlDecorator;

   /**
    * Contains all the fields that have references to this instance and are usually created by the widget initialization code
    */
   ref ?:StateNx2Ref;

   /**
    * Sibling(s) of the main anchor that will be rendered before the main anchor
    */
   prefixSiblings?:Elem_or_Nx2[];

   /**
    * Sibling(s) of the main anchor that will be rendered after the main anchor
    */
   siblings ?:Elem_or_Nx2[];

   /**
    * The current children this widget contains
    */
   children?: Elem_or_Nx2[];


   /**
    * If this is true, the widget will be rendered without using the <link>tagId</link> value as the id of the HTML element.
    * @see tagId
    */
   noTagIdInHtml?: boolean;

   // /**
   //  * Set to true if the existing HTMLElement needs to be destroyed and recreated when refreshing
   //  */
   // resetUIOnRefresh?: boolean;

   /**
    * If true, the resize is tracked for the HTML element of the widget
    */
   resizeTracked?: boolean;


   // /**
   //  * Set to true if the widget is completely static and no refresh should take place
   //  */
   // staticWidget?: boolean;

   /**
    * The unique id of the widget (also used as the id of the HTML element if <link>noTagIdInHtml</link> is false)
    * @see noTagIdInHtml
    */
   tagId?: string;

   /**
    * The id of the wrapper element around the HTML element of the widget
    * Defined as `${tagId}_wrapper` by default
    */
   wrapperTagId ?: string;

   // onClear?: (args:Nx2Evt_OnClear) =>  void ;

   onDestroy?: (ev: Nx2Evt_Destroy) =>  void ;

   onHtml?: (ev:Nx2Evt_OnHtml) =>HTMLElement;

   onLogic?: (ev : Nx2Evt_OnLogic) =>  void;

   // onRefresh?: (args ?: Nx2Evt_Refresh) =>  void;
   /**
    * Called when the widget is resized (assuming <link>widget.resizeTracked</link> is true)
    * @param evt
    */
   onResized ?: (ev?:Nx2Evt_Resized) => void;

   widgetErrorHandler?: WidgetErrorHandler;

   onBeforeInitHtml ?: (ev: Nx2Evt_OnHtml) => void;
}

export interface StateNx2Ref {

   /**
    * the htmlElement (usually generated by <link>onHtml</link>) that underpins the widget. This is a generated property (usually)
    */
   htmlElement ?: HTMLElement;

   widget?: Nx2;



}